### ISSUE TITLE
Please avoid loading non-libraries using provide

### ISSUE THREAD

**Issue by tarsius** [sviridov/undercover.el-buttercup-integration-example#1]
Test and setup files are not really libraries and therefore should not provide a feature.

Instead of providing a feature in those files and then loading them using `require`, such files should be loaded using `(load-file "path/to/file.el")`.

Such files *can* provide features if you really really want to, but in that case their names (and thus the provided features) have to follow the naming conventions for "support libraries", which is to name them `PACKAGE-SUBFUNCTIONALITY.el`.

---

Not doing either of those things is problematic for individual packages. When doing it in an example configuration it is a recipe for disaster. This example contains files like `undercover-init.el` (providing `undercover-init`), which only works properly as long as there is only one package following these suggestions.

As soon as there are two packages that do it, there are also two `undercover-init`. If a user has both of these packages installed and then runs the test coverage check for either one of these packages, then it is undefined which of the two `undercover-init.el` is loaded by `(require 'undercover-init)` - it depends on the order of the `load-path`.

---

I think the only proper fix here is to stop `provide`ing and `require`ing these files and using `load-file` instead. Additionally - since this is an example project - you should not just remove the `provide` forms, but replace those with an explanation of why one shouldn't use one. E.g. by linking here.

`ert-runner` had a similar issue in the past: https://github.com/rejeep/ert-runner.el/issues/38. I would appreciate it if you could address this soon before a large amount of packages are affected.

Thanks!

**Comment by tarsius** [comment]
Affected packages:

- [x] adafruit-wisdom https://github.com/gonewest818/adafruit-wisdom.el/pull/1
- ~~[flycheck-pos-tip](https://github.com/flycheck/flycheck-pos-tip) (not contacted yet)~~ Not sure why I though this had the same issue.

**Comment by sviridov** [comment]
Hi @tarsius, thanks for the explanation.

Fixed it for:
- undercover.el-buttercup-integration-example
- undercover.el-combined-usage-example

**Comment by tarsius** [comment]
So we are done, right?

**Comment by sviridov** [comment]
Yes, I think so.

**Comment by tarsius** [comment]
Wehee ;-)
